import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Inter } from 'next/font/google'
 
const inter = Inter({ subsets: ['latin'] })
import "./globals.css";

export const metadata: Metadata = {
  title: "Chaitanya Chaurasia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col bodymain ${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
